feat: add LNB and Header layout
Co-Laon/claon-admin-web pull request #45
Opened 2023-05-02 05:12 UTC by ywj3493

## Related issue
resolves #35 

## Description
1. Add LNB layout and Header layout

## Changes detail

1. Add LNB Component and related variables and types
    - Add const variables about LNB detail informations.
    - Add interface and type and enum variables.
    ![admin-web-35-1](https://user-images.githubusercontent.com/37992140/235583940-2a220568-88e5-4c14-818f-569e2cfc4729.gif)

2. Add Header

### Checklist

- [ ] Test case
- [ ] End of work

2023-05-02 06:23 UTC, LUCAssYA commented on src/components/common/header/HeaderDepth.tsx
> +interface HeaderDepthProps extends React.HTMLAttributes<HTMLElement> {
depth1Name, depth2Name으로 나누기 보다는 string 배열로 props를 받는게 좀 더 깔끔하지 않을까라는 생각을 해보았습니다.

2023-05-02 06:23 UTC, LUCAssYA commented on src/pages/main/index.tsx
> +import LNB from '@/components/common/LNB/LNB';
LNB와 헤더는 로그인 회원가입하는 화면 말고는 모두 보여야하는 화면이 아닌가요..? main/index.tsx에 파일 놔두면 자동적으로 보이게 되나요...?

2023-05-02 06:23 UTC, LUCAssYA commented on src/components/common/LNB/LNBItems.tsx
> +}: LNBDepth1Props) {
나중에 기획이 바뀌어서 2-depth가 아닌 더 깊은 구조가 될 수도 있고 이 트리를 다른 곳에서 쓸 수도 있어서 좀 더 확장성 있게 바꾸는게 어떨까라는 생각을 잠깐 해보았지만 지금 구조가 괜찮은 것 같습니다.

2023-05-02 08:22 UTC, qowlsdn8007 commented on src/components/common/AlarmedIcon/AlarmedIcon.tsx
> +function AlarmedIcon({ children, count }: AlarmedIconProps) {
Badge라는 명칭은 어떨까요?   아이콘 위의  숫자 등 알림을 뱃지라고도 하더라구여

2023-05-02 08:22 UTC, qowlsdn8007 commented on src/utils/LNBManage.ts
> +import { LNBMenu } from '@/types/common.d';
메뉴 관련 텍스트 따로 관리하는거 굳 아이디어같아요!

그런데 이는 utils가 아닌  constants라는 폴더를 따로 두고 관리하면 의미가 더 맞을거 같아요

2023-05-02 08:22 UTC, qowlsdn8007 commented on src/pages/main/index.tsx
> +import LNB from '@/components/common/LNB/LNB';
레이아웃으로 관리되는게 맞겠네요

2023-05-02 10:32 UTC, ywj3493 commented on src/components/common/LNB/LNBItems.tsx
> +}: LNBDepth1Props) {
저도 이 점은 민수님께 문의했던건데, depth3 이상으론 안 간다고 확답을 하셔서 현재 구조로 했습니다. 나중에 추가될 것 같으면 그때 고치시져

2023-05-02 10:33 UTC, ywj3493 commented on src/components/common/AlarmedIcon/AlarmedIcon.tsx
> +function AlarmedIcon({ children, count }: AlarmedIconProps) {
그럼 BadgedIcon 으로 이름 바꾸는게 좋을 것 같네요. 그렇게 변경하도록 하겠습니다.

2023-05-02 10:39 UTC, ywj3493 commented on src/components/common/header/HeaderDepth.tsx
> +interface HeaderDepthProps extends React.HTMLAttributes<HTMLElement> {
string 배열로 받게된다면 코드는 깔끔해 질 수 있지만 추후 작업할 때 어떤 값이 어떤 의미를 가지는지 이해하기 어렵지 않을까요? 해당 파일에서 props 에 들어가는 값을 알아야지만 해당 파일의 코드를 정확하게 이해 할 수 있게 될 것 같아서요. 근데 코멘트를 달면서 제가 재민님 코멘트를 잘못 이해 한 것 같다는 생각이 살짝 드네요... 혹시 예시를 들어주실 수 있으신가요...?

2023-05-02 10:39 UTC, ywj3493 commented on src/pages/main/index.tsx
> +import LNB from '@/components/common/LNB/LNB';
아 그게 맞습니다. 이건 제가 인지하고도 처리를 안 한 부분 이네요. 고치겠습니다.

2023-05-02 10:40 UTC, ywj3493 commented on src/utils/LNBManage.ts
> +import { LNBMenu } from '@/types/common.d';
그게 더 좋을 것 같네요!

2023-05-03 01:39 UTC, LUCAssYA commented on src/components/common/header/HeaderDepth.tsx
> +interface HeaderDepthProps extends React.HTMLAttributes<HTMLElement> {
depth1Name depth2Name 을 합쳐서 name: [depth1Name, depth2Name] 이런 식으로 props를 받는것을 말한 것 입니다.

2023-05-03 05:50 UTC, ywj3493 commented on src/components/common/header/HeaderDepth.tsx
> +interface HeaderDepthProps extends React.HTMLAttributes<HTMLElement> {
얘기해주신 것 보니 말씀하신게 더 좋은 방법 같습니다. 컴포넌트 구성 자체가 depth 랑 상관이 크게 없네요. 말씀하신 것 처럼 고치겠습니다.

2023-05-14 06:31 UTC, qowlsdn8007 requested changes

2023-05-14 06:31 UTC, qowlsdn8007 commented on src/components/common/LNB/LNBItems.tsx
> +}: LNBDepth1Props) {
같은 props를 가지되  optional한 값을 줘서  depth 별로 아이콘 등을 다르게 주는 형식으로 하면 어떨까요?

해서 컴포넌트는 나누지 말고 LNBItem 하나로 관리 하구요 !

2023-05-14 06:31 UTC, qowlsdn8007 commented on src/components/common/header/HeaderDepth.tsx
> +interface HeaderDepthProps extends React.HTMLAttributes<HTMLElement> {
회원관리 > 회원등급 관리라면,         ['회원관리', '회원 등급 관리' ]  로 받아서      join(' > ') 함수를 통해 하나의 문자열로 나타낼 수 도 있고 할 것 같네요.

저 depthname이 클릭 속성을 가지고 있다면 또 다른 얘기지만 단순 텍스트라면 재민님 방식이 더 깔끔할듯요

2023-05-14 06:31 UTC, qowlsdn8007 commented on src/components/common/LNB/LNBItems.tsx
> +}: LNBDepth1Props) {
네넵

2023-05-14 06:31 UTC, qowlsdn8007 commented on src/components/common/LNB/LNB.tsx
> -  onClickDepth2: (depth1Name: string, depth2Name: string, icon: string) => void;
LNB의 이벤트핸들러를  props를 통해서 받아서 처리해야만 하는 상황이 있는걸까요?   LNB 컴포넌트에서 자체적으로 가지고 있어도 될 것 같습니다.  책임을 분리하는 느낌으로 .ㅇ.ㅇ.

2023-05-14 06:31 UTC, qowlsdn8007 commented on src/components/common/header/Header.tsx
> +          depthArray={depthArray}
depth array를 통해 depth를 관리할거라면  depth1도 함께 관리할 수 있지 않을까 싶습니다.ㅇ.

2023-05-14 06:31 UTC, qowlsdn8007 commented on src/layouts/RootLayout.tsx
> +  const [selectedDepth2, setSelectedDepth2] = useState<HeaderDepthProps>({
처음 렌더링 되는 메뉴의 이름을 static하게 적용하기보단,    router props 정보 ?  등의 페이지를 판단할 수 있는 값으로 처리해주는 것은 어떨까요?

첫번째 페이지가 '암장 관리' 가 아니라면 해당 코드의 초기값을 변경해주어야 할 것 같아서요!

2023-05-14 06:31 UTC, qowlsdn8007 commented on src/layouts/RootLayout.tsx
> +  const [selectedDepth2, setSelectedDepth2] = useState<HeaderDepthProps>({
@ywj3493

2023-05-14 06:31 UTC, qowlsdn8007 commented on src/components/common/LNB/LNB.tsx
> -  onClickDepth2: (depth1Name: string, depth2Name: string, icon: string) => void;
@ywj3493

2023-05-14 06:31 UTC, qowlsdn8007 commented on src/components/common/header/Header.tsx
> +          depthArray={depthArray}
@ywj3493

2023-05-14 08:50 UTC, ywj3493 commented on src/components/common/LNB/LNB.tsx
> -  onClickDepth2: (depth1Name: string, depth2Name: string, icon: string) => void;
@qowlsdn8007 해당 사항 같은 경우는 결국 이건 컴포넌트고 layout 이나 page 에서 사용할 때를 위해서 props 로 만들어 둔 것이긴 합니다! LNB 자체는 state  같은 걸 가지지 않게 하기 위함이었어요. 왜냐하면 layout 에서 LNB 컴포넌트나 Header 컴포넌트가 동일한 선택된 메뉴 관련 state 를 가지게 되기 때문이고, 이 state 핸들러를 LNB 에 전달하기 위함 이었습니다. 책임 분리를 위해 recoil 을 사용해서 핸들러 자체를 LNB 에 두고 Header 는 해당 atom 을 구독하는 방식으로 변경 할 수 있을 것 같은데 그렇게 변경 할까요? 답변 주시면 변경하고 다시 커밋 하겠습니다.

2023-05-14 13:05 UTC, ywj3493 commented on src/components/common/LNB/LNB.tsx
> -  onClickDepth2: (depth1Name: string, depth2Name: string, icon: string) => void;
생각해보니 일단은 해당 레이아웃의 state 로 가지고 있는게 나을 것 같다는 생각이 들긴 하네요 다른 곳에서 글로벌 하게 사용할 일이 있을까 싶어서요... 다른부분 먼저 커밋 하고 요 건은 직접 말씀 드릴게요

2023-05-14 13:07 UTC, ywj3493 commented on src/components/common/header/Header.tsx
> +          depthArray={depthArray}
맞네요! 그렇게 변경했습니다!

2023-05-14 13:07 UTC, ywj3493 commented on src/layouts/RootLayout.tsx
> +  const [selectedDepth2, setSelectedDepth2] = useState<HeaderDepthProps>({
그게 맞는 방법인 것 같습니다. 반영했습니다!

2023-05-14 14:47 UTC, qowlsdn8007 commented on src/components/common/header/Header.tsx
> +          depthArray={depthArray}
확인했습니다! 고생하셨어요!

2023-05-14 15:04 UTC, qowlsdn8007 commented on src/components/common/LNB/LNB.tsx
> -  onClickDepth2: (depth1Name: string, depth2Name: string, icon: string) => void;
@ywj3493 LNB와 HEADER가 나누어져 있으니 처음 말씀하신대로 recoil에서 관리하는 것도 좋을거 같네요! 저두  같은 데이터를 공유하는 것을 간과하고 말씀드렸는데 좋은 아이디어입니다!!

2023-05-14 15:24 UTC, qowlsdn8007 commented on src/layouts/RootLayout.tsx
> +  const [selectedDepth2, setSelectedDepth2] = useState<HeaderDepthProps>({
@ywj3493  고생하셨습니다! 추가적으로  LNB의 버튼도 next/LINK를 쓰면 url을 바로 쓸 수 있지 않을까 합니다!

2023-05-15 00:11 UTC, ywj3493 commented on src/layouts/RootLayout.tsx
> +  const [selectedDepth2, setSelectedDepth2] = useState<HeaderDepthProps>({
감사합니다 그런데 이건 사실 레이아웃 커밋이라… 라우팅 관련해선 저희끼리 얘기 간단하게 하시고 추가하시죠! 다음 커밋에서 적용하겟습니다!

2023-05-15 08:40 UTC, qowlsdn8007 approved these changes

2023-05-15 08:40 UTC, merged