Issue12/refac
Co-Laon/claon-admin-web pull request #68
Opened 2023-07-12 10:48 UTC by ywj3493

## Related issue
resolves #issue12

## Description
refactor enterance manager page to combine step1 page and step2 page together.

## Changes detail

- delete route manager/step1, manager/step2
- add route manager

### Checklist

- [ ] Test case
- [ ] End of work

2023-07-16 08:26 UTC, LUCAssYA approved these changes, later dismissed

2023-07-16 08:35 UTC, LUCAssYA requested changes
따로 패키지가 추가되거나 버전이 바뀐게 아니라면 pnpm.lock파일을 다시 rollback 부탁드립니다!

2023-07-17 04:14 UTC, ywj3493 commented
> 따로 패키지가 추가되거나 버전이 바뀐게 아니라면 pnpm.lock파일을 다시 rollback 부탁드립니다!

넵 pnpm 메이저 버전이 달라서 생긴 문제였습니다. 해당 파일 rollback 하여 커밋했습니다!

2023-07-17 05:40 UTC, LUCAssYA approved these changes

2023-07-17 05:40 UTC, merged